rootProject.name = 'conductor-java-sdk'
include 'conductor-client'
include 'conductor-client-metrics'
include 'conductor-client-spring'
include 'tests'
include 'conductor-client-spring-boot4'
include 'harness'
include 'conductor-client-ai'
include 'conductor-client-ai-spring'
include 'agent-examples'
include 'e2e'
